- core/src/main/java/sem/group15/bubblebobble/core/objects/GravityObject.java
* Add set speedY to 0 when collided with a FloorObject.
* Removed magic numbers for gravity speed.
> Fix GravityObject

- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/WallObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
changed (test)handleCollision to use wallobjects
> fixed enemyObject tests with wallObjects

- core/src/main/java/sem/group15/bubblebobble/core/objects/BubbleObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
Create a correct random number generator such that the enemy gets a random x direction
and repaired the test for the handlecollision method.
> Remove bugs that caused the speed to be predetermined and inmuttable

- core/src/main/java/sem/group15/bubblebobble/core/LogicController.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/FilledBubbleObject.java
Handeling player-filledBubble collision with the isAlive flag
> Filledbubble collision

- core/src/main/java/sem/group15/bubblebobble/core/LogicController.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/BubbleObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
isAlive atributes for bubbleObject and enemyObject and updated checAlive method
> enemy and bubble collision

- .travis.yml
- core/src/test/java/sem/group15/bubblebobble/core/LoggerTest.java
> Add tests for Logger.

- core/src/main/java/sem/group15/bubblebobble/core/objects/GravityObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GravityObjectTest.java
Add line that fixes the window focus bug. Also wrote test for it.
> Fix window focus bug

- core/src/main/java/sem/group15/bubblebobble/core/objects/PlayerObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/PlayerObjectTest.java
Moving while death is impossible now. Also added a test. And created a function where a (future) death animation can be added.
> Fix death bug

- core/src/main/java/sem/group15/bubblebobble/core/objects/BubbleObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/FilledBubbleObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/GravityObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/PlayerObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GameObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GravityObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/PlayerObjectTest.java
- pom.xml
Added tests, features and done some refactoring.
> Test cases

- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/PlayerObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GameObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GravityObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/PlayerObjectTest.java
Refactored test classes for player, enemy and game.
> Refactor tests

- core/src/main/java/sem/group15/bubblebobble/core/objects/GravityObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/GravityObjectTest.java
- tmp.lvl
also added test case in gravityobject
> added warping and test <feature>

- core/src/main/java/sem/group15/bubblebobble/core/objects/BubbleObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/EnemyObject.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/EnemyObjectTest.java
Fix the bug that one bubble could catch multiple enemies. Also wrote a test for it.
> Fix double catch

- assets/levels/2.lvl
- assets/levels/3.lvl
- core/src/main/java/sem/group15/bubblebobble/core/Level.java
- core/src/main/java/sem/group15/bubblebobble/core/LogicController.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/PlayerObject.java
> Add logic to change levels if you win, and restart at level 1 if you die

- core/src/main/java/sem/group15/bubblebobble/core/Level.java
- core/src/main/java/sem/group15/bubblebobble/core/LogicController.java
level upobjects are never removed from map, just from gameObjects. So game so wouldnt level up when all enemies gone.
> change level to next one

- core/src/main/java/sem/group15/bubblebobble/core/objects/Enemy.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/StrongEnemy.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/StrongEnemyTest.java
tests for the new superenemy, and a few checkstyle fixes
<testing, layout
> Testing superenemy

- core/src/main/java/sem/group15/bubblebobble/core/LogicController.java
- core/src/test/java/sem/group15/bubblebobble/core/LogicControllerTest.java
> some tests for logic controller <testing

- core/src/main/java/sem/group15/bubblebobble/core/objects/Enemy.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/SimpleEnemy.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/StrongEnemy.java
> Enemy classes violated dry and solid principles.

- core/src/main/java/sem/group15/bubblebobble/core/objects/Fruit.java
Fruits now first have a little jump up
> Set initial speed <feature

- core/src/main/java/sem/group15/bubblebobble/core/GameController.java
- core/src/main/java/sem/group15/bubblebobble/core/gameStates/GameState.java
- core/src/main/java/sem/group15/bubblebobble/core/gameStates/LostState.java
- core/src/main/java/sem/group15/bubblebobble/core/gameStates/NewState.java
- core/src/main/java/sem/group15/bubblebobble/core/gameStates/PauseState.java
- core/src/main/java/sem/group15/bubblebobble/core/gameStates/PlayState.java
- core/src/test/java/sem/group15/bubblebobble/core/GameControllerTest.java
implemented state pattern, sorry @wouterz kind of messed up your test for GameController. <logic, organisation, testing>
> State pattern

- core/src/main/java/sem/group15/bubblebobble/core/GameController.java
- core/src/main/java/sem/group15/bubblebobble/core/LevelRenderer.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/GameState.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/LostState.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/NewState.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/PauseState.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/PlayState.java
- core/src/main/java/sem/group15/bubblebobble/core/gamestates/TransitionState.java
Still need to add some javadoc and stuff, but the idea is there, check it out
> Add transitions between levels. <feature

- core/src/main/java/sem/group15/bubblebobble/core/LevelParser.java
- core/src/main/java/sem/group15/bubblebobble/core/LevelRenderer.java
- core/src/main/java/sem/group15/bubblebobble/core/factories/EnemyFactory.java
- core/src/main/java/sem/group15/bubblebobble/core/factories/SimpleEnemyFactory.java
- core/src/main/java/sem/group15/bubblebobble/core/factories/StrongEnemyFactory.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/Enemy.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/FilledBubble.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/GameObject.java
- core/src/main/java/sem/group15/bubblebobble/core/objects/Player.java
- core/src/test/java/sem/group15/bubblebobble/core/LevelRendererTest.java
- core/src/test/java/sem/group15/bubblebobble/core/factories/SimpleEnemyFactoryTest.java
- core/src/test/java/sem/group15/bubblebobble/core/factories/StrongEnemyFactoryTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/FilledBubbleTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/PlayerObjectTest.java
- core/src/test/java/sem/group15/bubblebobble/core/objects/SimpleEnemyTest.java
tested whatever there was to be tested in objects, for this I did change enemyfactory parameters to include the state,
Also tested levelrenderer, pretty messy but was hard to test.
My branch has overal coverage of 84% as of now.
> Testing <testing

- core/src/main/java/sem/group15/bubblebobble/core/Assets.java
- core/src/main/java/sem/group15/bubblebobble/core/LevelRenderer.java
- core/src/test/java/sem/group15/bubblebobble/core/LevelRendererTest.java
> implement highscore in gui

- core/src/main/java/sem/group15/bubblebobble/core/GameController.java
- core/src/test/java/sem/group15/bubblebobble/core/GameControllerTest.java
Replaced gamecontroller tests since they didnt work after implementing GameStates
overal coverage of 79%
> replace gamecontroller tests <testing
